<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';
  
  type Product = {
    id?: number;             // Optional if it's generated by backend
    name: string;
    price: number;
    createdAt?: string;      // Optional because it's not set by user
  };
  
  let products: Product[] = [];
  let newProduct = { name: '', price: 0 };
  let loading = false;
  let apiUrl = 'http://localhost:5000/api';
  
  // Fetch products
  async function fetchProducts() {
    if (!browser) return;
    
    try {
      loading = true;
      const response = await fetch(`${apiUrl}/products`);
      products = await response.json();
    } catch (error) {
      console.error('Error fetching products:', error);
    } finally {
      loading = false;
    }
  }
  
  // Add new product
  async function addProduct() {
    if (!browser || !newProduct.name || newProduct.price <= 0) return;
    
    try {
      const response = await fetch(`${apiUrl}/products`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(newProduct)
      });
      
      if (response.ok) {
        newProduct = { name: '', price: 0 };
        await fetchProducts();
      }
    } catch (error) {
      console.error('Error adding product:', error);
    }
  }
  
  onMount(fetchProducts);
</script>

<svelte:head>
  <title>Docker + .NET Lab</title>
  <meta name="description" content="Demostración de containerización con .NET y SvelteKit" />
</svelte:head>

<main>
  <div class="container">
    <header>
      <h1>🐳 Docker + .NET Lab</h1>
      <p>Demostración de containerización con .NET y SvelteKit</p>
    </header>
    
    <section class="add-product">
      <h2>Agregar Producto</h2>
      <div class="form">
        <input 
          type="text" 
          placeholder="Nombre del producto" 
          bind:value={newProduct.name}
        />
        <input 
          type="number" 
          placeholder="Precio" 
          step="0.01"
          bind:value={newProduct.price}
        />
        <button on:click={addProduct}>Agregar</button>
      </div>
    </section>
    
    <section class="products">
      <h2>Productos ({products.length})</h2>
      
      {#if loading}
        <div class="loading">Cargando productos...</div>
      {:else if products.length === 0}
        <div class="empty">No hay productos. ¡Agrega el primero!</div>
      {:else}
        <div class="product-grid">
          {#each products as product}
            <div class="product-card">
              <h3>{product.name}</h3>
              <p class="price">${product.price}</p>
              <small>Creado: {product.createdAt ? new Date(product.createdAt).toLocaleString() : 'Desconocido'}</small>
            </div>
          {/each}
        </div>
      {/if}
    </section>
    
    <footer>
      <p>✅ API: .NET 8 + SQL Server | 🎨 Frontend: SvelteKit | 🐳 Container: Docker</p>
    </footer>
  </div>
</main>

<style>
  :global(body) {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
  }
  
  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    min-height: 100vh;
  }
  
  header {
    text-align: center;
    color: white;
    margin-bottom: 40px;
  }
  
  h1 {
    font-size: 3em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
  }
  
  .add-product {
    background: white;
    border-radius: 12px;
    padding: 25px;
    margin-bottom: 30px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.1);
  }
  
  .form {
    display: flex;
    gap: 15px;
    flex-wrap: wrap;
  }
  
  input {
    flex: 1;
    padding: 12px;
    border: 2px solid #e1e5e9;
    border-radius: 8px;
    font-size: 16px;
    min-width: 200px;
  }
  
  input:focus {
    outline: none;
    border-color: #667eea;
  }
  
  button {
    background: #667eea;
    color: white;
    border: none;
    padding: 12px 24px;
    border-radius: 8px;
    font-size: 16px;
    cursor: pointer;
    transition: all 0.3s;
  }
  
  button:hover {
    background: #5a6fd8;
    transform: translateY(-2px);
  }
  
  .products {
    background: white;
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.1);
  }
  
  .product-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
    margin-top: 20px;
  }
  
  .product-card {
    background: #f8f9fa;
    border: 1px solid #e9ecef;
    border-radius: 8px;
    padding: 20px;
    transition: transform 0.2s;
  }
  
  .product-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 4px 16px rgba(0,0,0,0.1);
  }
  
  .price {
    font-size: 1.5em;
    color: #28a745;
    font-weight: bold;
    margin: 10px 0;
  }
  
  .loading, .empty {
    text-align: center;
    padding: 40px;
    color: #6c757d;
    font-style: italic;
  }
  
  footer {
    text-align: center;
    margin-top: 40px;
    color: white;
    opacity: 0.8;
  }
  
  @media (max-width: 768px) {
    .form {
      flex-direction: column;
    }
    
    input {
      min-width: auto;
    }
    
    .product-grid {
      grid-template-columns: 1fr;
    }
  }
</style>